<?php

namespace Fixtures;

use PDO;
use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\CoversNothing;
use ShopingCart;

#[CoversNothing]
class ShopingCartTest extends TestCase
{
    protected $cart;
    protected static $db_connection = false;

    protected function setUp(): void
    {
        $this->cart = new ShopingCart();
    }

    protected function tearDown(): void
    {
        unset($this->cart);
    }

    public function testCorrectNumberOfItems(): void {
        $this->cart->addItem('one');
        $expected = 1;
        $result = $this->cart->amount;
        $this->assertEquals($expected, $result);
    }

    public function testCorrectProductName(): void {
        $this->cart->addItem('one');
        $this->assertContains('one', $this->cart->cartItems);
    }

    public static function setUpBeforeClass(): void {
        //parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        if (self::$db_connection) return;
        self::$db_connection = new \PDO('sqlite::database.db');
    }

    public static function tearDownAfterClass(): void {
        self::$db_connection = null;
        unlink(':database.db');
    }

}
